### PR TITLE
Upgrading cloudflare gem

### PR DESCRIPTION
**Pull request by gleseur**
Hi wk8,

Upgrading to 2.0.3
because we need this fix: https://github.com/b4k3r/cloudflare/pull/11

From https://github.com/b4k3r/cloudflare/compare/v2.0.1...master?w=1 changes are minor, just needs from https://github.com/b4k3r/cloudflare/pull/12 to be merged.

Thanks

### CODE REVIEW

**Comment by wk8** [comment]
Hi Guillaume,

Happy to merge this when v2.0.3 does get released to the official ruby gems repo, which does not seem to be the case:
```
gem list cloudflare --remote --all

*** REMOTE GEMS ***

[...]
cloudflare (2.0.2, 2.0.1, 2.0.0, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.0)
```

**Comment by pekhee** [comment]
2.0.3 is now officially released.

```
gem list cloudflare --remote --all

*** REMOTE GEMS ***

[...]
cloudflare (2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.0)
```

**Comment by wk8** [comment]
Sorry for taking so long, had forgotten about this :-( merging!

**Comment by wk8** [comment]
Released as v0.1.8: https://github.com/wk8/cookbook-cloudflare/releases/tag/0.1.8

**Pull request merged**
